kind: pipeline
name: default

steps:
  - name: build
      image: node:latest
      commands: npm install
  - name: release
    image: node:latest
    commands: npm run release
    when:
      event: tag