kind: pipeline
name: default

steps:
  - name: build
      image: node:latest
      commands: npm install
  - name: release
    image: node:latest
    environment:
      CONVENTIONAL_GITHUB_RELEASER_TOKEN:
        from_secret: key
    commands: npm run release
    when:
      event: tag