kind: pipeline
name: default

steps:
  - name: fetch
    image: node:latest
    commands:
    - git fetch --tags

  - name: build
    image: node:latest
    commands:
      - npm install

  - name: bump-version
    image: node:latest
    commands:
      - npm version ${DRONE_TAG} --no-git-tag-version
      - git config --global user.email "you@example.com"
      - git config --global user.name "Your Name"
      - git add package.json
      - 'git commit -m "chore: bump to ${DRONE_TAG}"'
      - git push origin HEAD:master
    when:
      event: tag

  - name: release
    image: node:latest
    environment:
      CONVENTIONAL_GITHUB_RELEASER_TOKEN:
        from_secret: key
    commands:
      - npm run release
    when:
      event: tag