kind: pipeline
name: default

steps:
  - name: build
    image: node:latest
    commands:
      - npm install
  - name: test-git
    image: node:latest
    commands:
      - git log
  - name: release
    image: node:latest
    environment:
      CONVENTIONAL_GITHUB_RELEASER_TOKEN:
        from_secret: key
    commands:
      - npm run release
    when:
      event: tag