pipeline:
  build:
    image: node:latest
    commands: npm install
  release:
    environment:
      CONVENTIONAL_GITHUB_RELEASER_TOKEN:
        from_secret: CONVENTIONAL_GITHUB_RELEASER_TOKEN
    image: node:latest
    commands: npm run release
    when:
      event: tag